# Generated by Django 5.1.2 on 2024-10-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_monument_created_at_monument_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='monument',
            name='designer_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='designer_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='owner_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='owner_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='polisher_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='polisher_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='stock_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monument',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
